### ISSUE TITLE
Write clear documentation explaining how the app works

### ISSUE THREAD

**Issue by aliblackwell** [bridgeatwaterloo/david#26]

**Comment by mabatistussi** [comment]
The application is to be used by Pell Ensemble, a contemporary dance company, for their interactive dance performance; David. The app allows the audience to choose the dancer's mood and movement through mobile interaction. The outcome is decided by the application's database taking either the majority or a random user. Within a 30 minute performance the audience has the possibility to make over 100 decisions.

It works by whenever a button is clicked on a question, a function runs which logs which decision the user has chosen and sends it to the firebase database. The function finishing with CurrentView(); runs when a button is clicked directing the user to the holding page. The function starting with CurrentView(); runs on the holding page preventing the user from going back to the question they have just answered. 

A function has been defined which listens to the database which means that whenever there is an input into the database, it will send the data back to this function. The function then processes the data and is able to give the results depending on what the audience member has chosen whether it needs to be a majority or a random user selected. This decision is then projected onto the three screens where the results are then seen by the audience and the dancer himself. Meanwhile the decisions should be seamless and the sound, projections and light all programmed to work on cue. 

The website gives a general overview and detailed information about the David performance. The user can find out about location, date and time.
The application connects, using interactive programming, the user and the performer. The first input required by the user is an username in order to log in. After that the projection will display an animated heart monitor line with the caption 'Bring David to life'. The user needs to input clicks to give a heartbeat to David and based on the average of clicks the speed of the heartbeat will increase. When David is alive the user need to answer if they are happy( yes or not). If yes the decision carries onto the next decision which is David's clothing if not it goes back from the beginner till the user answer yes. 
The decision of David's clothing will be decided based on the majority of their results. Again the audience will be asked from the user if they are happy or not. And the yes decision will carry on the decision to decide David's position. The user need to voted again and the majority will decided where David should go. 
The follow question will be asked is about the user want to more if yes the shows carry on if is not the shows end in there.

**Comment by mabatistussi** [comment]
Guys if anybody else want to add more details feel free!! tsk

**Comment by aliblackwell** [comment]
@mabatistussi this looks great! Could you please update the README.md and submit a pull request?
